
export interface TagOption {
  value: string
  label: string
}


export const TagOptions: readonly TagOption[] = [
  { value: 'react', label: 'React' },
  { value: 'nextjs', label: 'Nextjs' },
  { value: 'javascript', label: 'Javascript' },
  { value: 'typescript', label: 'Typescript' },
  { value: 'nodejs', label: 'Nodejs' },
  { value: 'express', label: 'Express' },
  { value: 'mongodb', label: 'MongoDB' },
  { value: 'mongoose', label: 'Mongoose' },
  { value: 'html', label: 'HTML' },
  { value: 'css', label: 'CSS' },
  { value: 'sass', label: 'SASS' },
  { value: 'tailwindcss', label: 'Tailwindcss' },
  { value: 'bootstrap', label: 'Bootstrap' },
  { value: 'materialui', label: 'MaterialUI' },
  { value: 'reactstrap', label: 'Reactstrap' },
  { value: 'reactnative', label: 'React Native' },
  { value: 'flutter', label: 'Flutter' },
  { value: 'dart', label: 'Dart' },
  { value: 'python', label: 'Python' },
  { value: 'django', label: 'Django' },
  { value: 'java', label: 'Java' },
  { value: 'spring', label: 'Spring' },
  { value: 'springboot', label: 'Spring Boot' },
  { value: 'springmvc', label: 'Spring MVC' },
  { value: 'Delphi', label: 'Fast and Powerful' },
  { value: 'csharp', label: 'C#' },
  { value: 'aspnet', label: 'ASP.NET' },
  { value: 'Arduino', label: 'Arduino' },
  { value: 'RaspberryPi', label: 'Raspberry Pi' },
  { value: 'Linux', label: 'Linux' },
  { value: 'Ubuntu', label: 'Ubuntu' },
  { value: 'Debian', label: 'Debian' },
  { value: 'Kali', label: 'Kali' },
  { value: 'Windows', label: 'Windows' },
  { value: 'MacOS', label: 'MacOS' },
  { value: 'Android', label: 'Android' },
  { value: 'IOS', label: 'IOS' },
  { value: 'SQL', label: 'SQL' },
  { value: 'MySQL', label: 'MySQL' },
  { value: 'PostgreSQL', label: 'PostgreSQL' },
  { value: 'Firebase', label: 'Firebase' },
  { value: 'AWS', label: 'AWS' },
  { value: 'GoogleCloud', label: 'Google Cloud' },
  { value: 'Azure', label: 'Azure' },
  { value: 'Docker', label: 'Docker' },
  { value: 'Kubernetes', label: 'Kubernetes' },
  { value: 'Git', label: 'Git' },
  { value: 'Github', label: 'Github' },
  { value: 'Bitbucket', label: 'Bitbucket' },
  { value: 'Gitlab', label: 'Gitlab' },
]