import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '@/styles/Home.module.scss'

import Link from 'next/link';
/* import { Button } from 'antd';
import "antd/dist/antd.dark.css" */


const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div>
          <Link href="/blog/create-new-blog">
            
            <span className='px-3 py-3 bg-blue-500 rounded-sm hover:bg-sky-700' >
              <span >New Blog</span> 
            </span>
          </Link>
        </div>
      </main>

      
    </div>
  )
}

export default Home
