name: sanskytech-CICD
'on':
  push:
      branches:
      - master
  pull_request:
      branches:
      - master

jobs:
    test:
        runs-on: self-hosted
        steps:
            - name: checkout 
              uses: actions/checkout@v3
            - name: 'use node.js ${{ matrix.node-version }}'
              uses: actions/setup-node@v3
              with: 
                node-version: latest
            - name: build project
              run: |
                yarn 
                yarn build
                pm2 restart nextjs --update-env
                pm2 save 
                sudo systemctl restart apache2.service 


